server:
  port: 8080

spring:
  datasource:
    items:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

debug: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
jwt:
  tokenIssuer: 'denis.nelubin@7bits.it'
  tokenSigningKey: 'abrakadabra'